credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$jaOKK36yZspC9DSbdfcYFeqL1aEfCoBVSpUECV1ktSTSMQUulBwq.
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$ATsXG4.riQjmCnXyya54HObf9Z4UX1870o8ronHiXib7gV6z2V7cO
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com